{{- if .Values.envoy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-http-proxy
  namespace: {{ .Values.envoy.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          networking.gke.io/load-balancer-type: "External"
{{- if .Values.gateway.ipv6.enabled }}
        loadBalancerIPs:
          -  "{{ .Values.gateway.ipv4.address }}"
          -  "{{ .Values.gateway.ipv6.address }}"
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
{{- else }}
        loadBalancerIP: "{{ .Values.gateway.ipv4.address }}"
{{- end }}

{{- end }}
