# templates/namespace.yaml
{{- if and (eq .Values.envoy.enabled true) (eq .Values.envoy.create_namespace true) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.envoy.namespace }}
{{- end }}
