certificate:
  create: true
  name: nip-io-cert
  namespace: default
  secretName: nip-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "34.46.182.72.nip.io"
    - "*.34.46.182.72.nip.io" # optional wildcard

issuer:
  create: true
  name: letsencrypt-prod
  email: esnet-stardust-dev@es.net
  server: https://acme-v02.api.letsencrypt.org/directory
  # Use staging for testing:
  # server: https://acme-staging-v02.api.letsencrypt.org/directory

gateway:
  create: true
  name: external-http
  namespace: default
  className: gke-l7-global-external-managed

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespacesFrom: All # All, Same, or Selector
    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespacesFrom: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: nip-io-tls # matches certificate.secretName
