apiVersion: v1
kind: Service
metadata:
  name: api-key-auth
  namespace:  {{ .Values.namespace }}
  labels:
    app: api-key-auth
spec:
  type: ClusterIP
  selector:
    app: api-key-auth
  ports:
    - port:  {{ .Values.ratelimiter.port }} 
      targetPort:  {{ .Values.ratelimiter.port }} 
      name: http
      protocol: TCP
