{{- if .Values.issuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: {{ .Values.gateway.name }}
            namespace: {{ .Values.gateway.namespace }}
            kind: Gateway
{{- end }}
