# values.yaml
namespace: dashboard

domains:
  - 34.59.30.245.nip.io

email: esnet-seg-ma@lbl.gov

envoy:
  enabled: true
  createNamespace: false
  namespace: envoy-gateway-system

gateway:
  enabled: true
  name: external-http
  namespace_policy: All
  className: gke-l7-global-external-managed
  ipv4:
    enabled: true
    address: 8.2.2.2
    address_type: NamedAddress
  ipv6:
    enabled: false
    address: "2600::"
    address_type: NamedAddress
  routes:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      use_tls: true
      mode: Terminate
      include_cert: true

certificate:
  name: tls-cert
  issuer: letsencrypt-prod
  staging: false
  use_gateway: true
  tlsPolicy:
    enabled: true
    name: gke-gateway-ssl-policy
    minVersion: "1.2"
    ciphers:
      - ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      - ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - ECDHE_ECDSA_WITH_AES_256_CBC_SHA
      - ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - ECDHE_RSA_WITH_AES_128_CBC_SHA
      - ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - ECDHE_RSA_WITH_AES_256_CBC_SHA
      - ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - RSA_WITH_AES_128_CBC_SHA
      - RSA_WITH_AES_128_GCM_SHA256
      - RSA_WITH_AES_256_CBC_SHA
      - RSA_WITH_AES_256_GCM_SHA384

extraResources: []
