apiVersion: v2
type: application
name: clickhouse
description: ClickHouse Cluster Configuration. Assumes the Altinity ClickHouse Operator is already installed (https://docs.altinity.com/clickhouse-operator/).
version: 0.0.9
appVersion: "25.9"
maintainers:
  - name: esnet
    email: "esnet-seg-ma@lbl.gov"
## This Chart may also be helpful: https://github.com/Altinity/helm-charts/tree/main/charts/clickhouse
