namespace: clickhouse

operator:
  enabled: true
  installCRDs: true

config:
  tls_enabled: true
  tls_cert_secret: tls-cert
  disk_volume_size: 1000Gi
  log_volume_size: 10Gi
  clickhouse_version: 25.9
  resources:
    chk:
      requests:
        memory: 256M
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 2

    ch:
      shardCount: 1
      replicasCount: 1
      requests:
        memory: 8Gi
        cpu: 4000m
      limits:
        memory: 16Gi
        cpu: 8000m

  domains:
    - localhost.nip.io

extraResources: []
