---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ .Values.config.kafka.clusterName }}
    {{- include "kafka.componentLabels" (list . "controller") | nindent 4 }}
spec:
  replicas: {{ .Values.config.keeper.controller.replicas }}
  storage:
    type: jbod
    volumes:
      {{- range .Values.config.keeper.controller.storage.volumes }}
      - id: {{ .id }}
        type: {{ .type }}
        size: {{ .size }}
        {{- if .kraftMetadata }}
        kraftMetadata: {{ .kraftMetadata }}
        {{- end }}
        deleteClaim: {{ .deleteClaim }}
      {{- end }}
  resources:
    limits:
      cpu: {{ .Values.config.keeper.controller.resources.limits.cpu | quote }}
      memory: {{ .Values.config.keeper.controller.resources.limits.memory }}
    requests:
      cpu: {{ .Values.config.keeper.controller.resources.requests.cpu | quote }}
      memory: {{ .Values.config.keeper.controller.resources.requests.memory }}
  template:
    pod:
      terminationGracePeriodSeconds: {{ .Values.config.keeper.controller.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/cluster: {{ .Values.config.kafka.clusterName }}
              strimzi.io/pool-name: controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - {{ .Values.config.kafka.clusterName }}-controller
              topologyKey: "kubernetes.io/hostname"
  roles:
    - controller
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ .Values.config.keeper.broker.name }}
  labels:
    strimzi.io/cluster: {{ .Values.config.kafka.clusterName }}
    {{- include "kafka.componentLabels" (list . "broker") | nindent 4 }}
spec:
  roles:
    - broker
  replicas: {{ .Values.config.keeper.broker.replicas }}
  resources:
    limits:
      cpu: {{ .Values.config.keeper.broker.resources.limits.cpu | quote }}
      memory: {{ .Values.config.keeper.broker.resources.limits.memory }}
    requests:
      cpu: {{ .Values.config.keeper.broker.resources.requests.cpu | quote }}
      memory: {{ .Values.config.keeper.broker.resources.requests.memory }}
  storage:
    type: jbod
    volumes:
      {{- range .Values.config.keeper.broker.storage.volumes }}
      - id: {{ .id }}
        type: {{ .type }}
        size: {{ .size }}
        {{- if .kraftMetadata }}
        kraftMetadata: {{ .kraftMetadata }}
        {{- end }}
        deleteClaim: {{ .deleteClaim }}
      {{- end }}
  template:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/cluster: {{ .Values.config.kafka.clusterName }}
              strimzi.io/pool-name: {{ .Values.config.keeper.broker.name }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - {{ .Values.config.kafka.clusterName }}-{{ .Values.config.keeper.broker.name }}
              topologyKey: "kubernetes.io/hostname"
