{{- range .Values.config.topics }}
---
apiVersion: kafka.strimzi.io/{{ $.Values.config.operator.crd_version }}
kind: KafkaTopic
metadata:
  name: topic-{{ .name | replace "_" "-" }}
  labels:
    strimzi.io/cluster: {{ $.Values.config.kafka.clusterName }}
    {{- include "kafka.componentLabels" (list $ "kafka-topic") | nindent 4 }}
spec:
  topicName: {{ .name }}
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    retention.ms: {{ .retention }}
{{- end }}
