config:
  argocd_annotation: false
  gateway:
    type: envoy
    class_name: envoy
    ipv4:
      enabled: true
      address_type: IPAddress
      address: "10.0.0.1"
    ipv6:
      enabled: true
      address_type: IPAddress
      address: "2001:db8::1"
  certificate:
    tlsPolicy:
      enabled: true
